// adultdutyassignments.js

const ADULT_ALLOWED_DUTY_ASSIGNMENTS = new Set([
  "Encampment Commander",
  "Encampment Commandant of Cadets",
  "Activity Director",
  "Activity Deputy Director",
  "Director",
  "Deputy Director",
  "Deputy Chief of Staff Aerospace Education",
  "Deputy Chief of Staff, Aerospace Education",
  "External Aerospace Education Officer",
  "Internal Aerospace Education Officer",
  "Cadet Advisory Council Senior Advisor",
  "Cadet Programs Development Officer",
  "Deputy Chief of Staff Cadet Programs",
  "Deputy Chief of Staff, Cadet Programs",
  "Chaplain",
  "Character Development Instructor",
  "Chief of Staff",
  "Commander",
  "Deputy Commander",
  "Public Affairs",
  "Director of Public Affairs",
  "Cadet Programs",
  "Director of Development",
  "Government Relations Advisor",
  "Health Services Officer",
  "Historian",
  "NCO Advisor",
  "Senior Enlisted Leader",
  "Deputy Chief of Staff Communications",
  "Deputy Chief of Staff, Communications",
  "Counterdrug Director",
  "Emergency Services Officer",
  "Emergency Services Training Officer",
  "Director of Finance",
  "Legal Officer",
  "Director of IT",
  "Web Security Administrator",
  "Inspector General",
  "Deputy Chief of Staff Logistics",
  "Deputy Chief of Staff, Logistics",
  "Maintenance Officer",
  "Transportation Officer",
  "CIS Officer",
  "Deputy Chief of Staff Operations",
  "Deputy Chief of Staff, Operations",
  "Homeland Security Officer",
  "Small Unmanned Aerial Systems Officer",
  "Assistant Standardization & Evaluation Officer",
  "Standardization & Evaluation Officer",
  "Director of Administration",
  "Director of Personnel",
  "Director of Plans and Programs",
  "Director of Plans & Programs",
  "Deputy Chief of Staff Education and Training",
  "Deputy Chief of Staff, Education and Training",
  "Director of Safety",
  "Aerospace Education Officer",
  "Cyber Education Officer",
  "Activities Officer",
  "Drug Demand Reduction Officer",
  "Fitness Officer",
  "Squadron Leadership Officer",
  "Advisor to the Commander",
  "Deputy Commander for Cadets",
  "Deputy Commander for Seniors",
  "Squadron NCO",
  "Communications Officer",
  "Disaster Preparedness Officer",
  "Search and Rescue Officer",
  "Finance Officer",
  "Information Technologies Officer",
  "Logistics Officer",
  "Supply Officer",
  "Public Affairs Officer",
  "Recruiting Officer",
  "Alerting Officer",
  "Operations Officer",
  "Administrative Officer",
  "Personnel Officer",
  "Education and Training Officer",
  "Testing Officer",
  "Safety Officer",
  "Director of Aerospace Education",
  "Director of Cadet Programs",
  "Drug Demand Reduction Administrator",
  "Encampment Commandant for Cadets",
  "Wing Chaplain Coordinator",
  "Diversity Officer",
  "Communications Engineering Officer",
  "Communications Licensing Officer",
  "Communications Training Officer",
  "Director of Communications",
  "Counterdrug Officer",
  "Director of Emergency Services",
  "Disaster Relief Officer",
  "Director of Logistics",
  "Director of Recruiting",
  "Director of Operations",
  "Plans and Programs Officer",
  "Director of Education and Training",
  "Assistant Deputy Chief of Staff, Aerospace Education",
  "Assistant Deputy Chief of Staff, Cadet Programs",
  "Assistant Deputy Chief of Staff, Communications",
  "Assistant Deputy Chief of Staff, Logistics",
  "Assistant Deputy Chief of Staff, Operations",
  "Assistant Deputy Chief of Staff, Education and Training",
  "National",
  "NHQ"
]);
