// cadetdutyassignments.js

export const cadetDutyAssignments = [
  "Cadet Activities NCO",
  "Cadet Activities Officer",
  "Cadet Administrative NCO",
  "Cadet Administrative Officer",
  "Cadet Aerospace Education NCO",
  "Cadet Aerospace Education Officer",
  "Cadet Commander",
  "Cadet Communications NCO",
  "Cadet Communications Officer",
  "Cadet Cyber Education NCO",
  "Cadet Cyber Education Officer",
  "Cadet Deputy Commander for Operations",
  "Cadet Deputy Commander for Support",
  "Cadet Element Leader",
  "Cadet Emergency Services NCO",
  "Cadet Emergency Services Officer",
  "Cadet Executive Officer",
  "Cadet Finance NCO",
  "Cadet Finance Officer",
  "Cadet First Sergeant",
  "Cadet Flight Commander",
  "Cadet Flight Sergeant",
  "Cadet Group Superintendent",
  "Cadet Historian",
  "Cadet Information Technology NCO",
  "Cadet Information Technology Officer",
  "Cadet Leadership Education NCO",
  "Cadet Leadership Education Officer",
  "Cadet Logistics NCO",
  "Cadet Logistics Officer",
  "Cadet Operations NCO",
  "Cadet Operations Officer",
  "Cadet Public Affairs NCO",
  "Cadet Public Affairs Officer",
  "Cadet Recruiting NCO",
  "Cadet Recruiting Officer",
  "Cadet Safety NCO",
  "Cadet Safety Officer",
  "Cadet Superintendent",
  "Cadet Testing NCO",
  "Cadet Testing Officer",
  "Cadet Training NCO",
  "Cadet Training Officer",
  "Cadet Advisory Council Chairperson",
  "Cadet Advisory Council Chairman",
  "Cadet Advisory Council Chairwoman",
  "Cadet Advisory Council Chair",
  "Cadet Advisory Council Vice Chair",
  "Cadet Advisory Council Recorder",
  "Primary Representative",
  "Cadet Chief of Staff",
  "Representative",
  "Assistant Representative"
];
